# Generated by Django 4.1.2 on 2022-10-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comments_text_comments_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='video_id',
            field=models.CharField(max_length=30),
        ),
    ]
